language: android
jdk: oraclejdk8

android:
    components:
        - tools
        - build-tools-23.0.2
        - android-23
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
        - extra-google-google_play_services
    licenses:
        - '.+'

script:
  - ./gradlew checkstyle build -Dpre-dex=false

sudo: false

cache:
    directories:
        - $HOME/.gradle/daemon
        - $HOME/.gradle/native
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
